language: "zh-CN"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  auto_title_placeholder: "@coderabbitai"
  commit_status: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches: ["main"]
chat:
  auto_reply: true