name: Split Repositories

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Input repo name to split, e.g. sentry, cache, etc.'
        required: false
        default: ''

jobs:
  split:
    name: Split on branch ${{ github.ref }}
    if: github.repository == 'friendsofhyperf/components'
    runs-on: ubuntu-22.04
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SPLIT_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Private Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Split And Push
        run: |
          git config pull.rebase true
          git config --global user.email "huangdijia@gmail.com"
          git config --global user.name "Deeka Wong"

          if [ -z "${{ github.event.inputs.repo }}" ]; then
            ./bin/split.sh
          else
            ./bin/split.sh ${{ github.event.inputs.repo }}
          fi